
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url:  <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: shortenter_development
  url: postgres://postgres@127.0.0.1:5432/
test:
  <<: *default
  database: shortenter_test
  url: postgres://postgres@127.0.0.1:5432/
production:
  <<: *default
